local render_helper = require "fixed_aspect_ratio.render_helper"

function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	msg.post(".", "release_input_focus")
end

function update(self, dt)
	msg.post("@render:", "draw_text", { text = "Click to spawn", position = vmath.vector3(20, 30, 0) })
end

function on_input(self, action_id, action)
	if action.released then
		factory.create("#factory", render_helper.action_to_position(action))
	end
end
