go.property("linear_velocity", 750)

local W = tonumber(sys.get_config("display.width"))
local H = tonumber(sys.get_config("display.height"))

function update(self, dt)
	local rotation = go.get_rotation()
	local distance = self.linear_velocity * dt
	local direction = vmath.rotate(rotation, vmath.vector3(0, distance, 0))
	local position = go.get_position() + direction
	go.set_position(position)
	if position.x < 0 or position.y < 0 or position.x > W or position.y > H then
		go.delete()
	end
end
