function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		if message.enter then
			self.marker_id = message.other_id
		else
			self.marker_id = nil
		end
	end
end

function on_input(self, action_id, action)
	go.set_position(vmath.vector3(action.x, action.y, 0))
	if action_id == hash("touch") and action.released and self.marker_id then
		msg.post("map:/controller", "marker_selected", { id = self.marker_id })
	end
end
